@startuml modelo de dominio

class PersonaConSintomas{
    nombre
    apellido
    numeroDni
}

class CentroDeAtencion{}
class LlamadoTelefonico{
    fecha
    hora
}
class Operador{}
class RegistroDeLlamado{}
class ListaDeSeleccionDeSintomas{}
class Sintoma{
    nombre
}
class NivelDeGravedad{
    nombre
}
class Recurso{}

class Telefono{
    codigoArea
    numero
}

class Domicilio{
    nombreCalle
    numero
}

'asociaciones'

Sintoma -- PersonaConSintomas: pertenecen a >
Sintoma -- ListaDeSeleccionDeSintomas: contenido en >
RegistroDeLlamado -- CentroDeAtencion: contenido en >

LlamadoTelefonico -- RegistroDeLlamado: se registra en >

Operador -- CentroDeAtencion: trabaja en >
Operador -- RegistroDeLlamado: gestiona >
Operador -- ListaDeSeleccionDeSintomas: utiliza >

PersonaConSintomas -- LlamadoTelefonico: realiza >
Operador -- LlamadoTelefonico: atiende >
NivelDeGravedad -- Sintoma: definido por >


Recurso -- CentroDeAtencion: pertenece al >
PersonaConSintomas -- Recurso: se le asigna >
PersonaConSintomas -- CentroDeAtencion: se comunica con >

Domicilio -- PersonaConSintomas: vivie en <
Telefono -- PersonaConSintomas: se la contacta mediante <
Telefono -- CentroDeAtencion: contacto del >

@enduml