@startuml modelo de dominio

class PersonaConSintomas{
    nombre
    apellido
    numeroDni
}

class CentroDeAtencion{}
class LlamadoTelefonico{
    fecha
    hora
}
class Operador{}
class RegistroDeLlamado{}
class ListaDeSeleccionDeSintomas{}
class Sintoma{
    nombre
}
class NivelDeGravedad{
    nombre
}
class Recurso{}

class Telefono{
    codigoArea
    numero
}

class Domicilio{
    nombreCalle
    numero
}

'asociaciones'

Sintoma "*" -- "1" PersonaConSintomas: pertenecen a >
Sintoma "*" -- "1" ListaDeSeleccionDeSintomas: contenido en >
RegistroDeLlamado "1" -- "1" CentroDeAtencion: contenido en >

LlamadoTelefonico "*" -- "1" RegistroDeLlamado: se registra en >

Operador "1" -- "1" CentroDeAtencion: trabaja en >
Operador "1" -- "1" RegistroDeLlamado: gestiona >
Operador "1" -- "1" ListaDeSeleccionDeSintomas: utiliza >

PersonaConSintomas "1" -- "1" LlamadoTelefonico: realiza >
Operador "1" -- "1" LlamadoTelefonico: atiende >
NivelDeGravedad "1" -- "*" Sintoma: definido por >

Recurso "1..3" -- "1" CentroDeAtencion: pertenece al >
PersonaConSintomas "1" -- "1" Recurso: se le asigna >
PersonaConSintomas "1" -- "1" CentroDeAtencion: se comunica con >

Domicilio "1" -- "1" PersonaConSintomas: vivie en <
Telefono "*" -- "1" PersonaConSintomas: se la contacta mediante <
Telefono "1" -- "1" CentroDeAtencion: contacto del >

@enduml