@startuml

actor Operador

Operador -> ":Sistema": iniciarNuevoRegistroDelLlamado()
":Sistema" --> Operador: presenta el ingreso del nombre y apellido
Operador -> ":Sistema": ingresarNombreYApellido(nombre, apellido)
":Sistema" --> Operador: presenta el ingreso del domicilio y teléfono
Operador -> ":Sistema": ingresarDomicilioYTelefono(domicilio, telefono)
":Sistema" --> Operador: habilita la confirmación de los datos ingresados
Operador -> ":Sistema": confirmarDatosPersonales()
":Sistema" --> Operador: presenta listado de selección de síntomas
loop mas sintomas
    Operador -> ":Sistema": seleccionarSintomaDeLaLista(sintoma)
    ":Sistema" --> Operador: lista actualizada
end
Operador -> ":Sistema": confirmarDatosIngresados()
":Sistema" --> Operador: nivel de gravedad, recurso asignado
@enduml
