@startuml


    Llamado -- RegistroDeLlamados: se registra en >
    Operador -- Llamado: atiende >
    PersonaConSintomas -- Llamado: realiza >
    Operador -- RegistroDeLlamados: registra el llamado en >
   

    PersonaConSintomas -- Sintoma: descripta por >
    Sintoma -- NivelDeGravedad: definen el >

    Recurso -- PersonaConSintomas: se le asigna a >
    PersonaConSintomas -- DatosPersonales: tiene >
    DNI -- DatosPersonales: forma parte de >
    Domicilio -- DatosPersonales: forma parte de >
    NumeroTelefonico -- DatosPersonales: forma parte de >

    Sintoma -- ListadoDeSintomas: contenidos en >
    ListadoDeSintomas -- Operador





    
    
@enduml
